# Generated by Django 4.1.1 on 2022-09-23 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0006_attribute_created_at_attribute_updated_at'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProuctAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_attribute_values', to='meta.attribute')),
            ],
        ),
    ]
