# Generated by Django 4.1.1 on 2022-09-23 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0006_attribute_created_at_attribute_updated_at'),
        ('product', '0002_prouctattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='prouctattributevalue',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='product.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prouctattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meta.attribute'),
        ),
    ]
