# Generated by Django 4.1.1 on 2022-09-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0006_attribute_created_at_attribute_updated_at'),
        ('product', '0003_prouctattributevalue_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProuctAttributeValue',
            new_name='ProductAttributeValue',
        ),
    ]
