# Generated by Django 4.1.1 on 2022-09-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_remove_attribute_max_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
