# Generated by Django 4.1.1 on 2022-09-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_attribute_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
