# Generated by Django 4.1.1 on 2022-09-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0004_attribute_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='min_values_count',
            field=models.IntegerField(default=1),
        ),
    ]
